### ISSUE TITLE
Installation/README.md  & ssh-keygen

### ISSUE THREAD

**Issue by DhyanRiktam** [sailfishos/docs.sailfishos.org#30]
**Problem**:
Sailfish SDK on windows needs "ssh-keygen.exe", whish is no more included in the following git install:

![grafik](https://user-images.githubusercontent.com/34177830/150963720-455b0451-db33-49a3-b989-960731533119.png)

**Solution**:    
Add the following instruction:

To install  "ssh-keygen.exe" inside MSYS2, run the command:
`        pacman -S openssh`

**Comment by martyone** [comment]
Interesting, in my MSYS2 installation it is still required:

```
$ pacman -Si git
Repository      : msys
Name            : git
Version         : 2.34.1-2
Description     : The fast distributed version control system
Architecture    : x86_64
[...]
Depends On      : curl  libpcre2_8  libexpat  libintl  vim  openssh  openssl
                  perl-Error  perl>=5.14.0  perl-Authen-SASL  perl-libwww
                  perl-MIME-tools  perl-Net-SMTP-SSL  perl-TermReadKey
[...]
```

Is there anything special about you MSYS2 installation?

**Comment by DhyanRiktam** [comment]
It seams i had installed other packages before: fortran, gcc, ...
Sorry, i can not reproduce it.

After uninstalling MSYS2 complitly & fresh install with git all is fine.
-> the ticket ist obsolete & closed
