### ISSUE TITLE
Slightly broken meta-page

### ISSUE THREAD

**Issue by Olf0** [sailfishos/docs.sailfishos.org#380]
This appears to be broken: https://github.com/sailfishos/docs.sailfishos.org/blob/master/Support/Help_Articles/Managing_Sailfish_OS/README.md#contents

**Comment by vigejolla** [comment]
Looks fine to me. The rendered version is here: [Managing Sailfish OS](https://docs.sailfishos.org/Support/Help_Articles/Managing_Sailfish_OS/)

**Comment by Olf0** [comment]
Ack!
Sorry, I cannot retrace what I saw / believed to see in September.
