### ISSUE TITLE
Link to hadk download broken

### ISSUE THREAD

**Issue by thigg** [sailfishos/docs.sailfishos.org#381]
https://github.com/sailfishos/docs.sailfishos.org/blob/127ccb30d7f0bd566ebcd8f40269e0f70a154797/Develop/HW_Adaptation/Sailfish_X_Xperia_Android_8_Build_and_Flash/README.md?plain=1#L22

Clicking the link shows no way to download anything.

**Comment by vige** [comment]
It is there. The HADK is really just the PDF, the link of which is under the "Read" headline.
